### ISSUE TITLE
Have blur pixels. How to fix it. MiLite 10 phone.

### ISSUE THREAD

**Issue by DmytroTsurkan** [BennyKok/PxerStudio#3]
![Screenshot_2021-03-16-20-33-19-891_com benny pxerstudio](https://user-images.githubusercontent.com/77736007/111363339-98b3c000-8698-11eb-895f-6c78b3e26c19.jpg)

**Comment by BennyKok** [comment]
I am also seeing this issues on my pixel 4a, not sure why too at this moment.

**Comment by DmytroTsurkan** [comment]
I think the problem is in this part of code. I do not understand, why we need raw array with zero data. 
` // Get the position
      
  final float mX = event.getX();
        final float mY = event.getY();
        final float[] raw = new float[9];
        drawMatrix.getValues(raw);

        final float scaledWidth = picBoundary.width() * mScaleFactor;
        final float scaledHeight = picBoundary.height() * mScaleFactor;

        picRect.set((int) (raw[Matrix.MTRANS_X])
                  , (int) (raw[Matrix.MTRANS_Y])
                  , (int) (raw[Matrix.MTRANS_X] + scaledWidth)
                  , (int) (raw[Matrix.MTRANS_Y] + scaledHeight)
        );

        if (!picRect.contains((int) mX, (int) mY)) {
            return true;
        }

        final int x = (int) (((mX - picRect.left) / (scaledWidth)) * picWidth);
        final int y = (int) (((mY - picRect.top) / (scaledHeight)) * picHeight);

        System.out.println(mX +" _ "+ picRect.left+ " _ " +scaledWidth +" _ " + picWidth);
        System.out.println(x +" <<x --- y>>"+ y);
        //We got x and y`

**Comment by DmytroTsurkan** [comment]
When drawing pixels in onDraw, everything fine. When draw after event, pixels has blur effect.
![Screenshot_2](https://user-images.githubusercontent.com/77736007/111459736-c3972600-8723-11eb-9079-7b571370ef43.png)
`@Override
    protected void onDraw(Canvas canvas) {
        canvas.drawColor(Color.parseColor("#FFFFFF"));
      
        canvas.save();
        canvas.concat(drawMatrix);
        canvas.drawBitmap(bgbitmap, null, picBoundary, pxerPaint);

        canvas.drawBitmap(bitmap, null, picBoundary, pxerPaint);

        canvas.drawPoint(200,200, pointPaint);
        canvas.drawPoint(170,170, pointPaint);
        canvas.drawPoint(270,140, pointPaint);
        canvas.drawPoint(270,180, pointPaint);`

**Comment by BennyKok** [comment]
Thanks!! @DmytroTsurkan I was away with native android dev for a while and left this project here for way too loooong time.
Thanks for spotting the problem, if you got time, you can do a pull request, but feel free anyway, I can get to update the repo any time in the near future.

**Comment by TacoTheDank** [comment]
@BennyKok Oh hey, if you're able to, could you please update the repo? The Play Store's last update was Dec 22, 2018 while the latest commit in the repo is from Nov 1, 2017, meaning some commits haven't been pushed upstream.

**Comment by BennyKok** [comment]
Hey @TacoTheDank thanks for wanting to help out, actually the last playstore update is just to disable the ads display from the ProjectManager view, since it's not really worth it that way for this project.

Anyway, I just fixed this #3 thanks to @DmytroTsurkan and spent the whole morning updating the dependencies and outdated library as you guys bring these issues up haha, I never thought I would download back Android Studio and work with native apps again.

Currently, there are still other problems after the heavy refactoring after almost 5 years, such as the changes of the file write permission of android over the years, so currently the file exported is in the app directory, and not easily visible to end-user, might have to work around for this issues later on.

also if you really look into the newer code, it's a bit messy, since I'm trying to get it back on running quickly.

Anyway feel free, i don't have any big plans on this project now.

**Comment by DmytroTsurkan** [comment]
Hi. The problem of blur pixels fixed on last android versiones, but returnes on lower android versiones. I will write, when fix it. And want to create brush like 2 by 2 pixels, 3 by 3. But no have idea, how to do this.

**Comment by DmytroTsurkan** [comment]
Blur fixed again.
In draw we must check android versione:
 ```
if (currentapiVersion <= Build.VERSION_CODES.P){
                canvas.drawBitmap(pxerLayers.get(i).bitmap, null, picBoundary, pxerPaint);
            } else{
                canvas.drawBitmap(pxerLayers.get(i).bitmap, null, picBoundary, null);
            }
```

**Comment by BennyKok** [comment]
Thanks, btw guys let me know would you think any of these be better if you like to make this work on the project in any way.
- I can directly add you guys to the contributor, 
- or create a team and move the project over there.
- or just creating pull request or leaving issues will be fine 

since I'm not actively working on the project at the moment, just feel free to let me know any thoughts.
